version: '3.8'

services:
  go_max:
    build: ./
    command: ./wait-for-postgres.sh db ./go_max
    ports:
      - 80:8000
    depends_on:
      - db
    environment:
      - DB_PASSWORD=9865guide

  db:
    restart: always
    image: postgres:latest
    volumes:
      - ./.database/postgres/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=9865guide
    ports:
      - 5436:5432
